import 'dotenv/config';

const {
    BOILER_DEV_PORT,
    BOILER_NODE_ENV,
    DATABASE_DEV_STRING,
    BOILER_DEV_PAPERTRAIL_HOST,
    BOILER_DEV_PAPERTRAIL_PORT
} = process.env;

export default {
    PORT: BOILER_DEV_PORT,
    NODE_ENV: BOILER_NODE_ENV,
    DATABASE_STRING: DATABASE_DEV_STRING,
    PAPERTRAIL_HOST: BOILER_DEV_PAPERTRAIL_HOST,
    PAPERTRAIL_PORT: BOILER_DEV_PAPERTRAIL_PORT
}