import 'dotenv/config';

const {
    BOILER_PROD_PORT,
    BOILER_NODE_ENV,
    DATABASE_PROD_STRING,
    BOILER_PROD_PAPERTRAIL_HOST,
    BOILER_PROD_PAPERTRAIL_PORT
} = process.env;

export default {
    PORT: BOILER_PROD_PORT,
    NODE_ENV: BOILER_NODE_ENV,
    DATABASE_STRING: DATABASE_PROD_STRING,
    PAPERTRAIL_HOST: BOILER_PROD_PAPERTRAIL_HOST,
    PAPERTRAIL_PORT: BOILER_PROD_PAPERTRAIL_PORT
}