import 'dotenv/config';

const {
    BOILER_TEST_PORT,
    BOILER_NODE_ENV,
    DATABASE_TEST_STRING,
    BOILER_TEST_PAPERTRAIL_HOST,
    BOILER_TEST_PAPERTRAIL_PORT
} = process.env;

export default {
    PORT: BOILER_TEST_PORT,
    NODE_ENV: BOILER_NODE_ENV,
    DATABASE_STRING: DATABASE_TEST_STRING,
    PAPERTRAIL_HOST: BOILER_TEST_PAPERTRAIL_HOST,
    PAPERTRAIL_PORT: BOILER_TEST_PAPERTRAIL_PORT
}